# Generated by Django 5.0.2 on 2026-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_names', models.CharField(max_length=1000)),
                ('topic_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='topic_names',
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='forum',
            field=models.CharField(max_length=1000),
        ),
    ]
