# Generated by Django 5.0.2 on 2026-08-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0002_topic_info_delete_topic_names_alter_forum_post_forum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forum_post',
        ),
    ]
