# Generated by Django 5.0.2 on 2026-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_App', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_info',
            name='system_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='topic_info',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
